class System:
    def __init__(self):
        raise NotImplementedError
    @staticmethod
    def xdot():
        raise NotImplementedError
    def get_pos_vec2(self):
        raise NotImplementedError
    def get_vel_vec2(self):
        raise NotImplementedError
    def get_theta(self):
        raise NotImplementedError
    def step(self):
        raise NotImplementedError
    def to_yaml(self):
        raise NotImplementedError
    def from_yaml(self):
        raise NotImplementedError
    def to_dict(self):
        raise NotImplementedError
